### ISSUE TITLE
Initializers are loaded before the application source

### ISSUE THREAD

**Issue by scottserok** [RenoFi/fishplate#10] opened 2019-12-27 20:57 UTC
When I try to access some of my applications constants inside of an initializer I'm getting a `NameError: uninitialized constant MyModel` exception.

```ruby
# config/initializers/test.rb
MyModel::SOME_CONSTANT
```

I believe in Rails this is possible (even AR database connection is ready [based on their documentation](https://guides.rubyonrails.org/v4.0/initialization.html) indicating intializers are loaded almost last). It would be nice to have access to source constants inside the initializers if it's an easy change that is low impact.

**Comment by scottserok** [comment] 2019-12-27 20:59
I think moving the first line to the last line of this method would solve the issue for me, but I'm not sure if there's a specific reason we have it first - https://github.com/RenoFi/fishplate/blob/8031c1561784344bc1918823b7fd5d39e7bdd297/lib/fishplate.rb#L42-L52

**Comment by knapo** [comment] 2019-12-28 12:11
@scottserok The problem is that initializers are loaded random order and moving lines around couldn't really fixed the issue. Since you're configuring zeitwerk autoloading in one of them, it really matter for classes visibility.

Btw, not sure if application constants should be used in initializers, if yes - maybe they should be defined there too ?

**Comment by knapo** [comment] 2019-12-28 12:11
It's fixed in https://github.com/RenoFi/fishplate/commit/3f5aad8af622716b0690260a3ebe78133e253500 and 1.0.1 is released.

**Closed by knapo** 2019-12-28 12:11 UTC

**Comment by scottserok** [comment] 2019-12-30 12:40
Slightly separate issue, but I'd like to use an ActiveRecord connection in an initializer. I think that's where the sequence of calls in `setup!` has an impact. What do you think?

**Comment by knapo** [comment] 2019-12-30 12:44
Yes, we can move it around, if you need.
